export type Product = {
  slug: string;
  name: string;
  category: string;
  price: number;
  originalPrice?: number;
  description: string;
  features: string[];
  specs: Record<string, string>;
  badge?: string;
  image: string;
  inStock: boolean;
};

export const categories = [
  "All",
  "CCTV & Surveillance",
  "Access Control",
  "Networking",
  "Cybersecurity",
  "Smart Home",
  "Software Licenses",
] as const;

export const products: Product[] = [
  {
    slug: "hikvision-ds-2cd2t87g2p-4k",
    name: "Hikvision DS-2CD2T87G2P 4K Bullet Camera",
    category: "CCTV & Surveillance",
    price: 45000,
    originalPrice: 55000,
    description:
      "Professional-grade 4K bullet camera with ColorVu technology, 40m IR range, IP67 weatherproofing, and built-in AI human/vehicle detection. Perfect for perimeter and outdoor surveillance.",
    features: [
      "4K Ultra HD (3840 x 2160) resolution",
      "ColorVu technology for full-color night vision",
      "40m IR distance",
      "AI-powered human & vehicle detection",
      "IP67 weatherproof rating",
      "H.265+ compression",
      "PoE support",
      "ONVIF compliant",
    ],
    specs: {
      Resolution: "4K (3840 x 2160)",
      "Sensor": "1/1.8\" Progressive Scan CMOS",
      "Lens": "2.8mm fixed",
      "IR Range": "40m",
      "Weatherproofing": "IP67",
      "Power": "PoE (802.3af) / 12V DC",
      "Storage": "MicroSD up to 256GB",
      "Dimensions": "100 × 100 × 295mm",
    },
    badge: "Best Seller",
    image: "/products/camera-1.svg",
    inStock: true,
  },
  {
    slug: "hikvision-ds-2de4a425iwg-t5-ptz",
    name: "Hikvision DS-2DE4A425IWG-T5 4MP PTZ",
    category: "CCTV & Surveillance",
    price: 185000,
    description:
      "4MP PTZ camera with 25x optical zoom, deep learning analytics, and 100m IR. Ideal for large-area monitoring such as parking lots, warehouses, and campus perimeters.",
    features: [
      "4MP resolution with 25x optical zoom",
      "100m IR distance",
      "Deep learning auto-tracking",
      "360° endless pan, -15° to 90° tilt",
      "Smart acquisition & face capture",
      "IP66 weatherproof",
      "H.265+ encoding",
      "PoE+ (802.3at)",
    ],
    specs: {
      Resolution: "4MP (2560 x 1440)",
      Zoom: "25x optical, 16x digital",
      "IR Range": "100m",
      Pan: "360° endless",
      Tilt: "-15° to 90°",
      "Weatherproofing": "IP66",
      "Power": "PoE+ (802.3at) / 24V AC",
      "Weight": "3.2kg",
    },
    image: "/products/camera-2.svg",
    inStock: true,
  },
  {
    slug: "hikvision-ds-k1t606m Facial Recognition Terminal",
    name: "Hikvision K1T606M Facial Recognition Terminal",
    category: "Access Control",
    price: 85000,
    description:
      "4.3-inch touchscreen facial recognition terminal with 99.7% accuracy, mask detection, and multi-factor authentication (face + card/PIN). Supports up to 50,000 faces.",
    features: [
      "99.7% facial recognition accuracy",
      "0.3s recognition speed",
      "Mask detection support",
      "Multi-factor auth (face + card/PIN)",
      "50,000 face capacity",
      "200,000 event records",
      "4.3-inch touchscreen display",
      "PoE / 12V DC powered",
    ],
    specs: {
      Display: "4.3-inch IPS touchscreen",
      "Face Capacity": "50,000",
      "Card Capacity": "50,000",
      "Recognition Speed": "< 0.3s",
      "Distance": "0.3m – 2m",
      "Interfaces": "RS-485, Wiegand, RJ45, USB",
      "Power": "12V DC / PoE",
      "Operating Temp": "-30°C to 60°C",
    },
    badge: "New",
    image: "/products/access-control-1.svg",
    inStock: true,
  },
  {
    slug: "fortinet-fortigate-40f",
    name: "Fortinet FortiGate 40F Next-Gen Firewall",
    category: "Cybersecurity",
    price: 125000,
    description:
      "Entry-level next-gen firewall delivering high-performance SD-WAN and security for small businesses and branch offices. Includes 1-year FortiGuard threat intelligence bundle.",
    features: [
      "4 Gbps firewall throughput",
      "9 Gbps IPS throughput",
      "Integrated SD-WAN",
      "FortiGuard threat intelligence (1-year)",
      "Web filtering & application control",
      "Intrusion prevention (IPS)",
      "SSL/TLS inspection",
      "FortiGate Cloud management",
    ],
    specs: {
      "Firewall Throughput": "4 Gbps",
      "IPS Throughput": "9 Gbps",
      "Interfaces": "10x GE RJ45",
      "Sessions": "700,000",
      "IPSec VPN": "4 Gbps",
      "Form Factor": "Desktop",
      "Power": "External adapter",
      "Dimensions": "216 x 150 x 33mm",
    },
    badge: "Popular",
    image: "/products/firewall-1.svg",
    inStock: true,
  },
  {
    slug: "ubiquiti-unifi-u6-pro",
    name: "Ubiquiti UniFi U6 Pro Access Point",
    category: "Networking",
    price: 28000,
    description:
      "Enterprise-grade Wi-Fi 6 access point with dual-band support, 5.3 Gbps aggregate throughput, and seamless roaming. Managed via UniFi Network application.",
    features: [
      "Wi-Fi 6 (802.11ax) dual-band",
      "5.3 Gbps aggregate throughput",
      "300+ concurrent clients",
      "Seamless roaming (802.11r)",
      "PoE+ powered",
      "Compact ceiling/wall mount",
      "Centralized UniFi management",
      "VLAN & guest portal support",
    ],
    specs: {
      Standard: "Wi-Fi 6 (802.11ax)",
      Bands: "2.4 GHz + 5 GHz",
      Throughput: "5.3 Gbps aggregate",
      "Max Clients": "300+",
      Range: "140m",
      Ports: "1x GbE RJ45",
      Power: "PoE+ (802.3at)",
      Mounting: "Ceiling / Wall",
    },
    image: "/products/access-point-1.svg",
    inStock: true,
  },
  {
    slug: "dell-poweredge-r750xs",
    name: "Dell PowerEdge R750XS Rack Server",
    category: "Networking",
    price: 650000,
    description:
      "2U rack server powered by Intel Xeon E-2300 series, supports up to 512GB DDR4 ECC, and offers flexible storage with 8x 2.5\" SAS/SSS bays. Ideal for virtualization, databases, and enterprise workloads.",
    features: [
      "Intel Xeon E-2300 series processor",
      "Up to 512GB DDR4 ECC RAM",
      "8x 2.5\" SAS/SATA/NVMe bays",
      "iDRAC9 Enterprise remote management",
      "Redundant 800W Platinum PSUs",
      "4x 1GbE + optional 10/25GbE",
      "Trusted Platform Module (TPM 2.0)",
      "5-year ProSupport warranty available",
    ],
    specs: {
      Processor: "Intel Xeon E-2300 series",
      Memory: "Up to 512GB DDR4 ECC",
      Storage: "8x 2.5\" SAS/SATA/NVMe",
      RAID: "PERC H755 SAS/NVMe",
      Networking: "4x 1GbE onboard",
      Remote: "iDRAC9 Enterprise",
      Power: "2x 800W Platinum PSU",
      Form: "2U Rack",
    },
    image: "/products/server-1.svg",
    inStock: true,
  },
  {
    slug: "sophos-xgs-1250w",
    name: "Sophos XGS 1250w Firewall",
    category: "Cybersecurity",
    price: 280000,
    description:
      "Next-generation firewall with dedicated Xstream Flow processor for high-performance TLS inspection. Perfect for mid-size enterprises needing advanced threat protection.",
    features: [
      "Xstream Flow Processor acceleration",
      "40 Gbps firewall throughput",
      "7.5 Gbps IPS throughput",
      "Deep learning threat protection",
      "Zero-day threat defense",
      "Synchronized Security with endpoints",
      "Cloud management via Sophos Central",
      "SD-WAN built-in",
    ],
    specs: {
      "Firewall Throughput": "40 Gbps",
      "IPS Throughput": "7.5 Gbps",
      "Interfaces": "8x GbE, 4x 10GbE SFP+",
      "Sessions": "4,200,000",
      "Users": "Unlimited",
      "Form Factor": "1U Rack",
      "Power": "Dual redundant PSU",
      "Warranty": "1-year hardware",
    },
    image: "/products/firewall-2.svg",
    inStock: true,
  },
  {
    slug: "microsoft-365-business-premium",
    name: "Microsoft 365 Business Premium (1 user/year)",
    category: "Software Licenses",
    price: 42000,
    description:
      "Annual license per user. Includes Office apps, Exchange email, Teams, 1TB OneDrive, Intune MDM, and Azure Information Protection. The complete security-focused productivity suite.",
    features: [
      "Office apps (Word, Excel, PowerPoint, Outlook)",
      "Microsoft Teams for meetings & chat",
      "Exchange Online (50GB mailbox)",
      "1TB OneDrive cloud storage",
      "Intune mobile device management",
      "Azure Information Protection",
      "Advanced Threat Protection",
      "Microsoft Defender for Business",
    ],
    specs: {
      Licensing: "Per user, annual",
      Storage: "1TB OneDrive",
      Email: "Exchange Online 50GB",
      Apps: "Desktop + Web + Mobile",
      "Device Management": "Intune MDM",
      "Security": "ATP + Defender",
      Support: "Microsoft 24/7 support",
      Updates: "Continuous",
    },
    badge: "License",
    image: "/products/software-1.svg",
    inStock: true,
  },
  {
    slug: "sonoff-smart-relay-4ch",
    name: "Sonoff 4CH Pro R3 Smart Relay",
    category: "Smart Home",
    price: 4500,
    description:
      "4-channel Wi-Fi smart relay with interlock, self-locking, inching and delay modes. Control 4 independent devices from the eWeLink app or via voice assistants.",
    features: [
      "4 independent relay channels",
      "Wi-Fi + RF 433MHz control",
      "Interlock / self-lock / inching modes",
      "Adjustable power-on delay",
      "Works with Alexa & Google Home",
      "eWeLink app remote control",
      "DIN rail mountable",
      "OTA firmware updates",
    ],
    specs: {
      Channels: "4",
      "Max Load": "10A per channel",
      Input: "AC 90-250V",
      Connectivity: "Wi-Fi 2.4GHz + RF 433MHz",
      Dimensions: "72 x 57 x 32mm",
      Mounting: "DIN rail / wall",
      Protocols: "eWeLink, Alexa, Google",
      Certification: "CE, FCC",
    },
    image: "/products/smart-home-1.svg",
    inStock: true,
  },
  {
    slug: "forticlient-edr-1-year",
    name: "FortiClient EDR — 50 endpoints / 1 year",
    category: "Software Licenses",
    price: 250000,
    originalPrice: 312500,
    description:
      "Endpoint Detection & Response for up to 50 devices. AI-driven threat detection, automated response, vulnerability scanning, and centralized FortiClient EMS management.",
    features: [
      "AI-driven endpoint detection & response",
      "Automated threat containment",
      "Vulnerability scanning & patching",
      "Centralized EMS cloud management",
      "USB device control",
      "Web filtering & application firewall",
      "Sandbox integration",
      "Compliance reporting",
    ],
    specs: {
      Endpoints: "50",
      Duration: "1 year",
      Detection: "AI + behavioral",
      Response: "Automated containment",
      Management: "FortiClient EMS / Cloud",
      OS: "Windows, macOS, Linux",
      Vulnerability: "Real-time scanning",
      Reporting: "SOC dashboard",
    },
    badge: "20% Off",
    image: "/products/software-2.svg",
    inStock: true,
  },
  {
    slug: "hikvision-ds-pwa64-lte-wireless-alarm-panel",
    name: "Hikvision DS-PWA64-LTE Wireless Alarm Panel",
    category: "Smart Home",
    price: 52000,
    description:
      "Professional wireless alarm panel with LTE connectivity, 64 zones, 32 remote key fobs, and Hik-Connect app integration. Supports PIR, door, smoke and flood sensors.",
    features: [
      "64 wireless zones",
      "LTE + Wi-Fi dual connectivity",
      "32 remote key fobs",
      "8 access codes + 1 master code",
      "Hik-Connect app integration",
      "SOS / panic button",
      "Battery backup (24h standby)",
      "Siren output (built-in + external)",
    ],
    specs: {
      Zones: "64 wireless",
      Connectivity: "LTE Cat 1 + Wi-Fi",
      "Key Fobs": "32",
      Codes: "8 user + 1 master",
      "Siren": "Built-in 85dB + external",
      Battery: "24h standby",
      Power: "12V DC adapter",
      Dimensions: "200 x 160 x 44mm",
    },
    image: "/products/smart-home-2.svg",
    inStock: true,
  },
  {
    slug: "cisco-catalyst-9200l-24p",
    name: "Cisco Catalyst 9200L 24-port PoE Switch",
    category: "Networking",
    price: 320000,
    description:
      "Enterprise managed PoE+ switch with 24x 1GbE ports, 120W PoE budget, Layer 3 Lite features, and Cisco DNA Center support. Reliable access-layer switching for offices and campuses.",
    features: [
      "24x 1GbE PoE+ ports",
      "120W PoE budget",
      "4x 1G SFP uplinks",
      "Layer 3 Lite (static routing)",
      "Cisco DNA Center ready",
      "StackWise-160 stacking",
      "Enhanced security (802.1X, TACACS+)",
      "Limited lifetime hardware warranty",
    ],
    specs: {
      Ports: "24x 1GbE PoE+",
      Uplinks: "4x 1G SFP",
      "PoE Budget": "120W",
      "Switching Capacity": "128 Gbps",
      Routing: "Layer 3 Lite",
      Stacking: "StackWise-160",
      Management: "CLI / DNA Center / cloud",
      Warranty: "Limited lifetime",
    },
    image: "/products/switch-1.svg",
    inStock: true,
  },
];
